name: ST-Warp
main: net.starly.warp.WarpMain
author: Starly Team
website: https://discord.gg/TF8jqSJjCG

version: 1.0.0
api-version: 1.16

softdepend: [ ST-Core ]

commands:
  warp:
    aliases: [ 워프 ]
    description: 워프 명령어
  spawn:
    aliases: [ 스폰 ]
    description: 스폰 명령어
  setspawn:
    aliases: [ 스폰설정 ]
    description: 스폰 설정 명령어
